export const products = [
  {
    id: 1,
    name: "Wireless Mouse",
    category: "Electronics",
    price: 25.99,
    stock: 150,
  },
  {
    id: 2,
    name: "Mechanical Keyboard",
    category: "Electronics",
    price: 89.99,
    stock: 45,
  },
  { id: 3, name: "Yoga Mat", category: "Fitness", price: 19.95, stock: 200 },
  {
    id: 4,
    name: "Stainless Steel Bottle",
    category: "Home & Kitchen",
    price: 15.0,
    stock: 320,
  },
  {
    id: 5,
    name: "Bluetooth Headphones",
    category: "Electronics",
    price: 59.5,
    stock: 85,
  },
  {
    id: 6,
    name: "Running Shoes",
    category: "Apparel",
    price: 120.0,
    stock: 60,
  },
  { id: 7, name: "Desk Lamp", category: "Furniture", price: 34.99, stock: 110 },
  {
    id: 8,
    name: "Organic Green Tea",
    category: "Groceries",
    price: 8.5,
    stock: 500,
  },
  {
    id: 9,
    name: "Leather Wallet",
    category: "Accessories",
    price: 45.0,
    stock: 75,
  },
  {
    id: 10,
    name: "Ceramic Coffee Mug",
    category: "Home & Kitchen",
    price: 12.99,
    stock: 140,
  },
  {
    id: 11,
    name: "Fitness Tracker",
    category: "Electronics",
    price: 49.99,
    stock: 95,
  },
  {
    id: 12,
    name: "Hiking Backpack",
    category: "Outdoors",
    price: 75.0,
    stock: 40,
  },
  {
    id: 13,
    name: "Cotton T-Shirt",
    category: "Apparel",
    price: 18.0,
    stock: 250,
  },
  {
    id: 14,
    name: "Gaming Chair",
    category: "Furniture",
    price: 199.99,
    stock: 20,
  },
  {
    id: 15,
    name: "Electric Kettle",
    category: "Home & Kitchen",
    price: 29.99,
    stock: 130,
  },
  {
    id: 16,
    name: "Wall Clock",
    category: "Home Decor",
    price: 22.5,
    stock: 85,
  },
  {
    id: 17,
    name: "Sunscreen SPF 50",
    category: "Personal Care",
    price: 14.25,
    stock: 180,
  },
  {
    id: 18,
    name: "Notebook (Pack of 3)",
    category: "Stationery",
    price: 10.99,
    stock: 300,
  },
  {
    id: 19,
    name: "Portable Power Bank",
    category: "Electronics",
    price: 35.0,
    stock: 115,
  },
  {
    id: 20,
    name: "Scented Candle",
    category: "Home Decor",
    price: 16.5,
    stock: 90,
  },
];
